version: '3.8'

services:
  app:
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run build && npm run start:prod"
    volumes: []  # Keine Volumes in Produktion, um Konflikte zu vermeiden

  db:
    ports:
      - "5432:5432"
